server:
  port: 8090
  servlet:
    session:
      timeout: 600
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-4y5a3gfo.sql.tencentcdb.com:20121/miaosha
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Czhlzyy520!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: 101.35.75.205
    port: 6379
    database: 0
    password: 123