server:
  port: 8090
  servlet:
    session:
      timeout: 600
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 31284679
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: 101.35.75.205
    port: 6379
    database: 0
    password: 123